checks:
    php: true

filter:
    excluded_paths: [Tests/*]

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
            other:
                after_type_cast: false

tools:
    external_code_coverage:
        timeout: 600
        runs: 3
